name: testci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/*'
jobs:
  build:
    runs-on: 'ubuntu:latest'

    steps:

    - name: git
      uses: actions/checkout@v4

    - name: setup
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: build
      run: go-build -o go-web-app
      
    
